import type { Project, Candidate, ClubUpdate, ExecutiveRole, PendingRegistration, ClubEvent, Moment, PendingProject, ClubMember, UserRole } from '../types';

export const libraryProjects: Project[] = [
    { id: 1, title: 'AI-Powered Learning Assistant', category: 'Tech for Education', description: 'An intelligent tutor for science students, providing personalized feedback.', longDescription: 'This project utilizes natural language processing and machine learning algorithms to create a dynamic learning environment. It integrates with existing course materials to offer students 24/7 assistance, track their progress, and identify areas where they need additional help. The backend is built with Python and FastAPI, while the frontend uses React and Tailwind CSS.', imageUrl: 'https://picsum.photos/seed/ai/500/400', tags: ['AI', 'React', 'Python', 'NLP'], githubLink: '#', liveDemo: '#', collaborators: ['Jane Doe', 'John Smith'] },
    { id: 2, title: 'Mobile Science Lab Outreach', category: 'STEM Education Outreach', description: 'Bringing hands-on science experiments to local schools using a mobile app.', longDescription: 'To bridge the gap in STEM education, this project developed a mobile application that guides students through safe, accessible science experiments using household materials. It includes video tutorials, quizzes, and a platform for students to share their results. The app is built with React Native for cross-platform compatibility.', imageUrl: 'https://picsum.photos/seed/outreach/500/400', tags: ['Mobile', 'Education', 'Community', 'React Native'], githubLink: '#', collaborators: ['Peter Jones'] },
    { id: 3, title: 'Automated Irrigation System', category: 'Innovation Sprints', description: 'A smart IoT device to optimize water usage in agriculture.', longDescription: 'This project is an IoT-based solution aimed at conserving water in local farms. It uses soil moisture sensors, weather forecast APIs, and an Arduino microcontroller to automatically manage irrigation schedules. A web dashboard allows farmers to monitor water usage and system status in real-time.', imageUrl: 'https://picsum.photos/seed/iot/500/400', tags: ['IoT', 'Arduino', 'Sustainability', 'Firebase'], githubLink: '#', liveDemo: '#', collaborators: ['Alice Johnson', 'Bob Williams'] },
    { id: 4, title: 'Collaborative Research Platform', category: 'Research Projects', description: 'A web platform for students to collaborate on research papers.', longDescription: 'This platform provides a centralized hub for student researchers to collaborate. Features include real-time document editing, version control, citation management, and a peer-review system. It is built on the MERN stack (MongoDB, Express, React, Node.js) and uses Socket.io for real-time features.', imageUrl: 'https://picsum.photos/seed/research/500/400', tags: ['Web', 'Collaboration', 'Node.js', 'MongoDB'], githubLink: '#', collaborators: ['Charlie Brown'] },
    { id: 5, title: 'Gamified Coding Tutor', category: 'Tech for Education', description: 'Learn Python basics through an interactive, game-like experience.', longDescription: 'This web-based platform makes learning to code fun and engaging for beginners. It features a series of challenges and quests that teach fundamental Python concepts. The platform includes a code editor, instant feedback, and a point-based reward system to motivate users.', imageUrl: 'https://picsum.photos/seed/gamify/500/400', tags: ['Gamification', 'Python', 'Web', 'Education'], githubLink: '#', collaborators: ['Emily White'] },
    { id: 6, title: 'Community Health Monitoring', category: 'STEM Education Outreach', description: 'A data visualization tool for local health trends.', longDescription: 'In partnership with the local clinic, this project aggregates anonymized health data and presents it on an interactive map. The goal is to help the community understand health trends and for our science education students to learn about data analysis. Built with D3.js and React.', imageUrl: 'https://picsum.photos/seed/health/500/400', tags: ['Data Viz', 'Health', 'D3.js', 'Community'], githubLink: '#', liveDemo: '#', collaborators: ['Frank Green', 'Grace Black'] },
    { id: 7, title: 'Renewable Energy Tracker', category: 'Innovation Sprints', description: 'Dashboard visualizing campus energy consumption and solar panel output.', longDescription: 'This project aims to promote energy conservation on campus by providing a real-time dashboard that displays energy usage from various buildings and the energy generated by the newly installed solar panels. It helps students and faculty understand their energy footprint. Built with Chart.js, React, and a Firebase backend.', imageUrl: 'https://picsum.photos/seed/energy/500/400', tags: ['IoT', 'Data Viz', 'React', 'Firebase'], githubLink: '#', liveDemo: '#', collaborators: ['David Lee', 'Sophie Turner'] },
    { id: 8, title: 'Virtual Chemistry Lab', category: 'Tech for Education', description: 'A simulation of common chemistry experiments for safe, remote learning.', longDescription: 'A web-based virtual laboratory where students can conduct chemistry experiments in a simulated environment. This tool is designed to supplement traditional labs, especially for hazardous reactions, providing a safe and accessible way to learn. Developed using Three.js for 3D graphics and React for the interface.', imageUrl: 'https://picsum.photos/seed/vrlab/500/400', tags: ['VR', '3D', 'Education', 'Three.js'], githubLink: '#', collaborators: ['Michael Clark'] },
    { id: 9, title: 'Code Mentorship Matcher', category: 'Research Projects', description: 'An algorithm to match junior developers with experienced mentors in the club.', longDescription: 'This project develops and implements a matching algorithm based on skills, interests, and availability to connect members for mentorship. It includes a user-friendly interface for sign-ups and a dashboard for mentors to manage their sessions. The goal is to foster skill development and a stronger community.', imageUrl: 'https://picsum.photos/seed/mentor/500/400', tags: ['Algorithm', 'Web', 'Community', 'Node.js'], githubLink: '#', liveDemo: '#', collaborators: ['Laura Wilson'] },
    { id: 10, title: 'Campus Event Aggregator', category: 'Innovation Sprints', description: 'A mobile app that pulls events from all campus departments into one calendar.', longDescription: 'This app solves the problem of scattered information by providing a unified calendar for all university events. It features filters, notifications for saved events, and integration with personal calendars. Built with Flutter and a Node.js backend that scrapes various campus websites.', imageUrl: 'https://picsum.photos/seed/aggregator/500/400', tags: ['Mobile', 'Flutter', 'API', 'Node.js'], githubLink: '#', liveDemo: '#', collaborators: ['James Taylor'] },
    { id: 11, title: 'Digital Herbarium', category: 'STEM Education Outreach', description: 'An online database of local plant species, created in collaboration with the Biology department.', longDescription: 'Students from Science Education and Computer Science collaborated to create a digital database of local flora. This project involved fieldwork to collect samples, image processing to digitize them, and web development to create a searchable, educational public website. Built with Django and PostgreSQL.', imageUrl: 'https://picsum.photos/seed/herbarium/500/400', tags: ['Biology', 'Web', 'Database', 'Django'], githubLink: '#', collaborators: ['Olivia Martinez', 'Daniel Harris'] },
];

export const votingProjects: Omit<Project, 'longDescription' | 'githubLink' | 'liveDemo' | 'collaborators'>[] = [
    { id: 7, title: 'Campus Companion App', category: 'Innovation Sprints', description: 'An all-in-one mobile app for campus navigation, class schedules, and event notifications.', imageUrl: 'https://picsum.photos/seed/app/500/400', tags: ['Mobile', 'React Native', 'Campus Life'] },
    { id: 8, title: 'Peer-to-Peer Tutoring Platform', category: 'Tech for Education', description: 'A platform connecting students who need academic help with those who can provide it.', imageUrl: 'https://picsum.photos/seed/tutor/500/400', tags: ['Web', 'Education', 'Community'] },
    { id: 9, title: 'Plastic Waste Upcycling Initiative', category: 'STEM Education Outreach', description: 'Developing low-cost methods to turn plastic waste into useful materials for schools.', imageUrl: 'https://picsum.photos/seed/plastic/500/400', tags: ['Sustainability', 'Chemistry', 'Community'] },
];

export const leaderCandidates: Candidate[] = [
    { id: 1, name: 'John Fulanki', position: 'CHAIRPERSON', imageUrl: 'https://picsum.photos/seed/john/200/200', vision: 'To foster a more inclusive environment and secure new industry partnerships for enhanced member opportunities.' },
    { id: 2, name: 'Jane Doe', position: 'CHAIRPERSON', imageUrl: 'https://picsum.photos/seed/jane/200/200', vision: 'My focus is on increasing inter-departmental collaboration and launching a dedicated mentorship program.' },
    { id: 3, name: 'Peter Jones', position: 'PROJECT_COORDINATOR', imageUrl: 'https://picsum.photos/seed/peter/200/200', vision: 'I will streamline the project submission and review process, ensuring faster feedback and more support for ongoing projects.' },
    { id: 4, name: 'Alice Johnson', position: 'TREASURER', imageUrl: 'https://picsum.photos/seed/alice/200/200', vision: 'I aim to improve financial transparency with monthly reports and explore new fundraising initiatives to support more ambitious projects.' },
    { id: 5, name: 'Bob Williams', position: 'TREASURER', imageUrl: 'https://picsum.photos/seed/bob/200/200', vision: 'My goal is to digitize all financial processes, making membership payments and budget requests seamless and efficient.' },
];

export let clubUpdates: ClubUpdate[] = [
    { id: 1, title: 'Q4 Innovation Sprint Announced: "Sustainable Tech"', date: 'Oct 15, 2024', author: 'Project Coordinator', content: 'Get ready for our final Innovation Sprint of the year! The theme is "Sustainable Tech". We are looking for innovative solutions to local environmental challenges. Registration opens next week. Start forming your teams now!' },
    { id: 2, title: 'Call for Mentors: STEM Outreach Program', date: 'Oct 12, 2024', author: 'Chairperson', content: 'Our STEM outreach program is expanding to two new local schools, and we need experienced members to act as mentors. This is a fantastic opportunity to give back to the community and develop your leadership skills. Please sign up by the end of the month.' },
    { id: 3, title: 'New Equipment in the CS Lab', date: 'Oct 10, 2024', author: 'Advisor', content: 'Thanks to a successful funding proposal, the CS Lab has been updated with new VR headsets and IoT development kits. These are available for all club members to use for their projects. Please see the lab technician for access.' },
    { id: 4, title: 'Membership Fee Reminder', date: 'Oct 5, 2024', author: 'Treasurer', content: 'A friendly reminder that annual membership fees are due by October 31st. You can now pay online through the portal. Your contribution is vital for funding our events and projects. Thank you for your support!' },
];

export const pendingRegistrations: PendingRegistration[] = [
    {
        id: 1,
        firstName: 'Grace',
        lastName: 'Phiri',
        studentId: 'DMI-20-001',
        email: 'grace.p@dmistc.com',
        program: 'BSc. Computer Science',
        year: 'Year 3',
        interests: ['AI / Machine Learning', 'Web & Mobile Development', 'Data Science & Analytics']
    },
    {
        id: 2,
        firstName: 'Samuel',
        lastName: 'Banda',
        studentId: 'DMI-21-002',
        email: 'samuel.b@dmistc.com',
        program: 'BEd. Science (Physics)',
        year: 'Year 2',
        interests: ['Physics & Renewable Energy', 'STEM Education Outreach', 'Electronics & Hardware']
    },
    {
        id: 3,
        firstName: 'Thokozani',
        lastName: 'Moyo',
        studentId: 'DMI-20-003',
        email: 'thoko.m@dmistc.com',
        program: 'BSc. Computer Science',
        year: 'Year 3',
        interests: ['Cybersecurity', 'Innovation & Entrepreneurship', 'UI/UX Design']
    }
];

export let events: ClubEvent[] = [
    { id: 1, title: 'Annual Science & Tech Fair', type: 'Competition', date: 'Oct 28, 2024', location: 'Main Auditorium', description: 'Showcase your projects and compete for amazing prizes.' },
    { id: 2, title: 'Intro to Machine Learning', type: 'Workshop', date: 'Nov 12, 2024', location: 'CS Lab 1', description: 'A hands-on workshop covering the fundamentals of ML with Python.' },
    { id: 3, title: 'Innovation Sprint: EdTech', type: 'Hackathon', date: 'Nov 25, 2024', location: 'Innovation Hub', description: 'A 48-hour hackathon to build solutions for education.' },
];

export const momentsData: Moment[] = [
  { id: 1, imageUrl: 'https://res.cloudinary.com/unihousingmw/image/upload/v1759762794/20251006_152255_p1cokt.jpg', caption: 'Members collaborating during the 2023 Annual Hackathon.' },
  { id: 2, imageUrl: 'https://picsum.photos/seed/moment2/1920/1080', caption: 'Our team presenting their project at the National Tech Fair.' },
  { id: 3, imageUrl: 'https://picsum.photos/seed/moment3/1920/1080', caption: 'A hands-on robotics workshop for first-year students.' },
  { id: 4, imageUrl: 'https://picsum.photos/seed/moment4/1920/1080', caption: 'Guest lecture from a leading software engineer in the industry.' },
  { id: 5, imageUrl: 'https://picsum.photos/seed/moment5/1920/1080', caption: 'Celebrating the launch of our new mentorship program.' },
  { id: 6, imageUrl: 'https://picsum.photos/seed/moment6/1920/1080', caption: 'Students from a local school engaging in our STEM outreach program.' },
  { id: 7, imageUrl: 'https://picsum.photos/seed/moment7/800/600', caption: 'The winning team of the Innovation Sprint proudly showcasing their trophy.' },
  { id: 8, imageUrl: 'https://picsum.photos/seed/moment8/800/600', caption: 'A lively discussion during a panel on the future of AI in education.' },
  { id: 9, imageUrl: 'https://picsum.photos/seed/moment9/800/600', caption: 'Late-night coding session fueled by pizza and passion.' },
  { id: 10, imageUrl: 'https://picsum.photos/seed/moment10/800/600', caption: 'The executive committee planning the calendar for the upcoming semester.' },
  { id: 11, imageUrl: 'https://picsum.photos/seed/moment11/800/600', caption: 'A member demonstrating their IoT project to the club advisor.' },
  { id: 12, imageUrl: 'https://picsum.photos/seed/moment12/800/600', caption: 'Club members networking with industry professionals after a seminar.' },
];

export const pendingProjects: PendingProject[] = [
    { id: 10, title: 'Campus Navigation AR App', category: 'Innovation Sprints', description: 'Augmented reality app to help new students navigate the campus.', submittedBy: 'Alex Green', tags: ['AR', 'Mobile', 'React Native'] },
    { id: 11, title: 'Automated Lab Assistant Bot', category: 'Tech for Education', description: 'A chatbot to assist students with lab procedures and safety protocols.', submittedBy: 'Maria Hill', tags: ['Chatbot', 'AI', 'Python'] },
];

const createMockUser = (id: number, name: string, email: string, role: UserRole, executiveRole?: ExecutiveRole, status: 'active' | 'pending' | 'suspended' = 'active', customImage?: string): ClubMember => ({
    id,
    name,
    email,
    role,
    executiveRole,
    studentId: `DMI-${22 - (id % 4)}-${String(id).padStart(3, '0')}`,
    joinDate: `202${2 - (id % 3)}-${String((id % 12) + 1).padStart(2, '0')}-15`,
    membershipStatus: status,
    profile: {
        firstName: name.split(' ')[0],
        lastName: name.split(' ').slice(1).join(' ') || 'User',
        profileImage: customImage || `https://i.pravatar.cc/150?u=${email}`,
        bio: `A passionate member of the DMIS&TC community, exploring the world of ${role === 'MEMBER' ? 'tech' : role.toLowerCase()}.`,
        skills: ['JavaScript', 'React', 'Node.js'],
        interests: ['STEM', 'Innovation', 'Collaboration'],
        socialLinks: { github: '#', linkedin: '#', twitter: '#' }
    }
});

export const clubMembers: ClubMember[] = [
    createMockUser(1, 'Emily Carter', 'emily.c@dmistc.com', 'MEMBER'),
    createMockUser(2, 'Benjamin Lee', 'ben.l@dmistc.com', 'MEMBER'),
    createMockUser(3, 'Olivia Rodriguez', 'olivia.r@dmistc.com', 'MEMBER', undefined, 'suspended'),
    createMockUser(4, 'Angel Kautsi', 'angie@gmail.com', 'EXECUTIVE', 'CHAIRPERSON'),
    createMockUser(5, 'Jane Alex', 'alexjane@gmail.com', 'EXECUTIVE', 'PROJECT_COORDINATOR'),
    createMockUser(6, 'Takondwa Chinkombero', 'teekay@gmail.com', 'EXECUTIVE', 'TREASURER'),
    createMockUser(7, 'Yohane H. Maluwa', 'ymaluwa@gmail.com', 'EXECUTIVE', 'COMMUNICATION_OFFICER', 'active', 'https://res.cloudinary.com/unihousingmw/image/upload/v1757151733/Yohane_jvzdlm.jpg'),
    createMockUser(8, 'Crusade Chiwalo', 'crvsade@hotmail.com', 'ADVISOR'),
    createMockUser(9, 'Admin User', 'admin@dmistc.com', 'ADMIN'),
    createMockUser(10, 'Yohane H. Maluwa', 'ymaluwa@gmail.com', 'SYSTEM_ADMIN'),
    createMockUser(11, 'Mason Taylor', 'mason.t@dmistc.com', 'MEMBER'),
    createMockUser(12, 'Ava Martinez', 'ava.m@dmistc.com', 'MEMBER'),
];

export const financialData = {
    income: [
        { source: 'Membership Fees', amount: 500000 },
        { source: 'Sponsorships', amount: 750000 },
        { source: 'Workshops', amount: 150000 },
    ],
    expenses: [
        { category: 'Event Hosting', amount: 300000 },
        { category: 'Project Supplies', amount: 450000 },
        { category: 'Marketing', amount: 100000 },
        { category: 'Software Licenses', amount: 50000 },
    ],
    get totalIncome() { return this.income.reduce((sum, item) => sum + item.amount, 0) },
    get totalExpenses() { return this.expenses.reduce((sum, item) => sum + item.amount, 0) },
    get netBalance() { return this.totalIncome - this.totalExpenses },
};